### ISSUE TITLE
npm entry outdated?

### ISSUE THREAD

**Issue by zerok** [afloyd/mongo-migrate#35]
Hi :-)

First of all thank you for your work on this project! I came here through npm and was quite surprised to see quite a big difference between what version is listed there (0.1.0) and the changes to the package.json that happened over the last 12 months since 0.1.0 had been pushed there.

Was this just an oversight that 0.2.0 and in January 1.0.0 were never pushed to npm or is some huge refactoring going on right now? :-)

**Comment by afloyd** [comment]
Yes there is a big disconnect between NPM and the repo... I was previously employed at a company and published to NPM through my work email. This repo is under my personal github so I can still access/update it. So my best advice if you want to use it is to either reference the commit in your package.json you want to use, or fork the repo and create an NPM from which you can pull.

I haven't actually done much work on this in a couple years... It's really been the community contributing and I've just accepted/merged the pull requests from them

Best wishes,
Austin

**Comment by zerok** [comment]
OK, thanks :)
