### ISSUE TITLE
Version on npmjs is outdated

### ISSUE THREAD

**Issue by siboulet** [afloyd/mongo-migrate#38]
I'm confused, the version on npmjs is still 0.1.0.

https://www.npmjs.com/package/mongo-migrate

_npm install mongo-migrate_ is pulling 0.1.0.

Any chances you can publish 1.2.0?

**Comment by afloyd** [comment]
Please see issue #35 for details...

**Comment by afloyd** [comment]
Solved: https://github.com/afloyd/mongo-migrate/commit/04215fdb628cfa5b3618ae8d7193b12e5c2dd994

Changed NPM package name to mongodb-migrate
