### ISSUE TITLE
verror is not defined

### ISSUE THREAD

**Issue by siboulet** [afloyd/mongo-migrate#41]
When database connection failed

ReferenceError: verror is not defined
    at /app/node_modules/mongodb-migrate/index.js:268:21

ReferenceError: verror is not defined
    at /app/node_modules/mongodb-migrate/index.js:275:22

**Comment by TimJohns** [comment]
Got it, I will fix that today

**Comment by afloyd** [comment]
Fixed with f04331e456f84b5323a4515f14772a9213e257df

**Comment by siboulet** [comment]
Please can you npm push 1.2.1

**Comment by marcdahan** [comment]
nowadays add : 

     var VError = require('verror');
