### ISSUE TITLE
migrate on heroku (and mongoLab)

### ISSUE THREAD

**Issue by kolodkin** [afloyd/mongo-migrate#43]
after successfully migrating changes in db on local host , i couldn't duplicate migration on heroku where my app is deployed.

I run the script throw heroku console:
heroku run "node ./node_modules/mongodb-migrate -runmm -cfg migration-config.json up"

what should be in the configuration file under host, db and port?

**Comment by kolodkin** [comment]
issue solved.
i migrated the change from my local PC to MogoLab database using the following configuration .json

{
  "mongoAppDb": {
    "host": <host>,
    "db": <dbname>,
    "port": <port>,
    "username": <username>,
    "password": <pass>
  }
}

taking variables value from heroku MongoLAB url (using heroku config) where the url format is as follows:
mongodb://<user>:<pass>@<host>:<port>/<dbname>

**Comment by afloyd** [comment]
Great work glad you were able to figure it out!
