### ISSUE TITLE
The command name is `mongo-migrate`, not `node mongodb-migrate`

### ISSUE THREAD

**Issue by halt-hammerzeit** [afloyd/mongo-migrate#51]
I suggest you update the README to say `mongo-migrate` instead of `node mongodb-migrate`.
`mongo-migrate` works when run via `npm run` scripts.

**Comment by halt-hammerzeit** [comment]
A follow up: there's a typo in capital I
`--runMongoMIgrate` -> `--runMongoMigrate`

**Comment by raiyankamal** [comment]
I just sent a PR to fix the typo https://github.com/afloyd/mongo-migrate/pull/53 .
